FROM eclipse-temurin:21-jdk
WORKDIR /app

# Uygulama JAR'ını kopyala
COPY build/libs/router-1.0-all.jar app.jar

# Uygulama portunu expose et
EXPOSE 6003

# Loglar için karakter seti ayarla (isteğe bağlı)
ENV LANG C.UTF-8

CMD ["java", "-cp", "app.jar", "router.Main"]

# JAR'ı çalıştır
ENTRYPOINT ["java", "-jar", "app.jar"]
