FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY build/libs/router-1.0-all.jar app.jar

EXPOSE 6003

ENV LANG C.UTF-8

CMD ["java", "-cp", "app.jar", "router.Main"]

ENTRYPOINT ["java", "-jar", "app.jar"]
