version: '3.8'

networks:
  simnet:
    driver: bridge

services:
  router:
    build:
      context: ../backend/router
      dockerfile: ../../docker/Dockerfile-router
    container_name: router
    networks:
      - simnet
    ports:
      - "6003:6003"

  server:
    build:
      context: ../backend/server
      dockerfile: ../../docker/Dockerfile-server
    container_name: java-message-server
    image: java-message-server:latest
    networks:
      - simnet

  client:
    build:
      context: ../backend/client
      dockerfile: ../../docker/Dockerfile-client
    container_name: java-message-client
    image: java-message-client:latest
    depends_on:
      - server
    networks:
      - simnet

  flask-api:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile-flask
    container_name: flask-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    depends_on:
      - server
    networks:
      - simnet

  react-ui:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile-frontend
    container_name: react-ui
    ports:
      - "3000:80"
    depends_on:
      - flask-api
    networks:
      - simnet
